select = ["E", "W", "F", "N", "D", "ANN", "A", "COM", "C4", "UP", "PT", "RET", "SIM"]
ignore = [
    "ANN101", "ANN204", "ANN206",
    "D105", "D107", "D203", "D205", "D212", "D401", "D407",
]
line-length = 99
