version: '3'
services:
  bash:
    build: .
    working_dir: /code
    volumes:
      - .:/code
    env_file:
      - .openai_template.env
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  # api:
  #   build: .
  #   working_dir: /code
  #   volumes:
  #     - .:/code
  #   ports:
  #     - "8080:8080"
  #   command: uvicorn source.service.api:app --host 0.0.0.0 --port 8080
  # streamlit:
  #   build: .
  #   working_dir: /code
  #   volumes:
  #     - .:/code
  #   ports:
  #     - "8501:8501"
  #   command: streamlit run source/service/app.py
